### ISSUE TITLE
Building a custom-op on Windows

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/custom-op#24] opened 2019-06-26 12:56 UTC
A heavily requested feature for tensorflow/addons is that we package a windows version:
https://github.com/tensorflow/addons/issues/173

AFAIK to build this we'll need a `libtensorflow_framework.dll` of some sort within the pip installed package. Looking at the link flags & installed directory it looks like this is not available.
```
python -c "import tensorflow as tf; print(tf.version.VERSION)"
2.0.0-beta1

python -c "import tensorflow as tf; print(tf.sysconfig.get_link_flags())"
[]
``` 

Is this by design or has it just not been implemented yet? There is a `_pywrap_tensorflow_internal.pyd` but I don't believe we've been linking to the python shared objects so I figured I was headed down the wrong path.

cc @meteorcloudy @yifeif @perfinion

**Comment by gunan** [comment] 2019-07-02 16:46
@allenlavoie do you remember why we chose to not have libtensorflow_framework on windows.

**Comment by allenlavoie** [comment] 2019-07-02 16:54
We were still using CMake on Windows when I made the change originally, so I just changed the Bazel builds. I imagine there are issues with the number of symbols libtensorflow_framework.dll would need to expose, but it's worth figuring out if we can support custom ops this way on Windows too.

**Comment by seanpmorgan** [comment] 2019-07-10 17:23
@gunan @allenlavoie Thanks for the followup. Is there anything I can do to help this along? (e.g. file an issue on tensorflow/tensorflow). I could try to start working on a PR myself but my time on windows boxes is limited and building TF from source won't be super efficient.

**Comment by gunan** [comment] 2019-07-14 21:12
I think we need to make all the changes around libtensorflow_framework for windows. I can see that the code just skips windows cases, for example here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L391

**Comment by amitport** [comment] 2019-10-23 15:34
is anyone working on this?

IMO this should have a very high priority.
 
This block fixes to a tf@2 regression for people trying to update tensorflow 1 that are using windows and tf.image. They now need tensorflow_addons which does not support windows because of this issue

**Comment by yifeif** [comment] 2019-10-25 18:37
Much thanks to @meteorcloudy 's investigation, here is a tentative todo-list paraphrased below:

- [ ] Build `tensorflow_framework` with symbols exported (example [commit](https://github.com/meteorcloudy/tensorflow/commit/1082fac875b378cdcfa34af9bbe9499ceadec77e) by @meteorcloudy )
- [ ] optionally make TensorFlow windows pip package build non-monolithic
- [ ] Include `.dl`l and `.lib` files of `tensorflow_framework` in the pip package
- [ ] Make `configure.sh` and `tf_configure.bzl` be aware of Windows. To use the `tensorflow_framework.dll.if.lib` for linking, you can use the [`cc_import`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) rule.
- [ ] Make `build_pip_pkg.sh` script work on Windows. Might need to do something similar to TF's [`build_pip_package.sh`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/build_pip_package.sh#L95) script as unfiles is disabled on Windows by default.
- [ ] Figure out how does `\<custom_op\>.so` find `tensorflow_framework.dll` at runtime. Do we need `.pyd` suffix (we might not if we use `tf.load_op_library`).

Let us know if you are interested in helping out with any of this.

**Comment by amitport** [comment] 2019-10-25 20:06
IMHO this is a critical regression (influencing all usage of APIs that moved from tf.contrib to tfa) not a 'contribution welcome' thing. I appreciate what is been done here by maintainers and I do realise this is open source, but from a practical perspective, tf seems like a bad choice for Windows users as its support is clearly not well tested and is not a priority for the tf team.

**Comment by yifeif** [comment] 2019-10-25 21:35
Thanks for the feedback @amitport. Just to clarify, we do care about Windows support, and plan to add it soon. We are marking this as contribution welcome in case anybody gets to pieces of this sooner. 

We are going to update the checklist as we make progress, most likely after TF World next week. cc: @martinwicke @jakline.

**Comment by jkyl** [comment] 2019-12-02 20:55
@seanpmorgan commented [yesterday:](https://github.com/tensorflow/addons/issues/173#issuecomment-560123048)
> Please forward your request comments/support to the custom-op issue: tensorflow/custom-op#24 so that it can be prioritized. The roadmap has been laid out, but it needs to be completed.

Just reiterating this request from the above-linked issue discussion, as instructed. This represents a significant feature regression for Windows users, and deserves a big bump in priority IMO.

**Comment by yifeif** [comment] 2019-12-06 00:08
Thanks for the patience! This should now work for CPU, and GPU support is on its way.

**Comment by yifeif** [comment] 2019-12-06 00:12
FYI, currently we are still using pywrap_tensorflow instead of tensorflow_framework under the hood for windows, but this detail should be taken care of by the macros.

**Closed** 2019-12-21 01:45 UTC
Labels: contributions welcome

**Comment by yifeif** [comment] 2019-12-21 01:46
Windows gpu support has also been added. Let me know if you run into any issue with it.

**Comment by TristanGottschalk** [comment] 2020-12-09 10:20
Hey guys! I am completely new to the implementation of custom ops. Can some please give me insides about how to build a custom op for windows? I found the tutorial for building an op for linux, but I do not understand, where I need to make changes in order to make it work for windows! Is there a dedicated tutorial to implement and use an op for windows? That would really help!

Thank you for your help!
